function [q,K,F,S,Sbar,empty] = chebyCheck_shockRank(restr,phi,opt)
% Function checks whether there exists a value of q satisfying the sign
% and zero restrictions using Algorithm 1, which extends the approach from
% Amir-Ahmadi and Drautzburg (2020) to allow for zero restrictions.
% Inputs:
% - restr: structure containing information about restrictions
% - phi: structure containing reduced-form VAR parameters
% - opt: structure containing model information and options

signRestr = restr.signRestr;
eqRestr = restr.eqRestr;
shockRankRestr = restr.shockRank;
U = restr.U;
Sigmatr = phi.Sigmatr;
Sigmatrinv = phi.Sigmatrinv;
vma = phi.vma;

n = size(Sigmatr,1); % Number of variables in VAR
s = size(signRestr,1); % Number of sign restrictions (excluding normalisation)
r = size(eqRestr,1); % Number of zero restrictions
T = size(restr.U,2); % Length of time series

% Options for linear programming routine.
lpoptimOptions = optimoptions('linprog');
lpoptimOptions.Display = 'off';

%% Construct matrix representing zero restrictions.
% Restrictions are represented as F(phi)*q = 0.

F = zeros(r,n);

for ii = 1:r

    if eqRestr(ii,3) == 1 % Restriction on A0

        F(ii,:) = Sigmatrinv(:,eqRestr(ii,2))';

    elseif eqRestr(ii,3) == 2 % Restriction on A0^(-1)

        F(ii,:) = Sigmatr(eqRestr(ii,1),:);

    elseif eqRestr(ii,3) == 3 % Restriction on LRCIR

        % Reshape VAR coefficients into matrix.
        B = reshape(phi.B,size(phi.B,1)/n,n);
        B = B(1:end-opt.nExog,:); % Drop coefficients on exogenous variables
        B = reshape(B',[n,n,opt.p]); % Reshape into array

        % Compute matrix of reduced-form LRCIRs post-multiplied by Sigma_tr.
        lrcir = ((eye(n)-sum(B,3))\eye(N))*Sigmatr;
    
        % Extract relevant row.
        F(ii,:) = lrcir(eqRestr(ii,1),:);

    end

end

%% Construct matrix representing sign restrictions.
% Restrictions are represented as S(phi)*q >= 0.

S = zeros(s+1,n);

for ii = 1:s % For each restriction
    
    if signRestr(ii,5) == 1 % Sign restriction on impulse response
    
        S(ii,:) = vma(signRestr(ii,1),:,signRestr(ii,3)+1)*signRestr(ii,4);
    
    elseif signRestr(ii,5) == 2 % Sign restriction on A0
        
        S(ii,:) = Sigmatrinv(:,signRestr(ii,2))'*signRestr(ii,4);
        
    end
    
end

S(end,:) = Sigmatrinv(:,1)'; % Add sign normalisation

%% Construct matrix representing shock-rank restriction.
%  Restrictions are represented as SR(phi)*q >= 0.

inds = shockRankRestr(1); % Index of restricted period    
otherInds = setdiff(1:T,inds); % Indices of other periods   
SR = (Sigmatrinv*(U(:,inds)-U(:,otherInds)))'; 

if shockRankRestr(1,2) == 1 % If absolute shock-rank restriction

    SR = [SR; (Sigmatrinv*(U(:,inds(1))+U(:,otherInds)))'];

end

SR = [SR; (Sigmatrinv*U(:,inds(1)))']; % Add shock-sign restriction
SR = shockRankRestr(3)*SR; % Adjust for sign of shock    

%% Combine traditional sign restrictions with shock-rank restrictions.
S = [S; SR];

s = size(S,1); % Total number of inequality restrictions
           
%% Transform restrictions so that algorithm from AD20 can be applied.
% Compute change of basis matrix.
K = [null(F), null(null(F)')];

% Apply change of basis to coefficient vectors in sign restrictions.
Stilde = (K'*S')'; % Note that K^{-1} = K' since K is orthonormal

% Project sign restrictions onto hyperplane generated by zero restrictions.
b = [zeros(r,n-r), eye(r)]';
B = eye(n) - b*((b'*b)\b');
Sbar = (B*Stilde')';

Sbar = Sbar(:,1:(n-r)); % Drop last f elements (which are zero)

%% Solve for Chebyshev centre.
% Find the centre and radius of the largest ball that can be inscribed
% within the intersection of the half-spaces generated by the (projected)
% sign restrictions and the unit cube in n-f dimensions.

A = zeros(s+1,n-r+1);
A(1:end-1,2:end) = -Sbar;

for ii = 1:(s+1)

    A(ii,1) = norm(A(ii,2:end));

end

A(end,1) = -1; % Add constraint that radius is positive

% Add additional restrictions that ball lies inside unit (n-f)-cube.
A = [A; [ones(n-r,1), eye(n-r)]; [ones(n-r,1), -eye(n-r)]];

% Problem is to maximise a*x s.t. A*x <= b, with x = (R,c')'.
a = [-1, zeros(1,n-r)]; % 
b = [zeros(s+1,1); ones(2*(n-r),1)];
x = linprog(a,A,b,[],[],[],[],lpoptimOptions);

% Check if radius is positive (i.e. if set is nonempty).
if x(1) > 0
    
    empty = 0;
    % Rescale Chebychev center so it lies on unit sphere.
    q = x(2:end)./norm(x(2:end));
    
else
    
    empty = 1;
    q = [];

end

end